// The variables the message engine understands, for the dashboard and any other tool that
// lets people write messages. utils/embedVariables.js is what actually resolves them; the check
// in scripts/check-embed-variables.js fails when the two disagree, so this list cannot drift.
//
// availability says where a variable has a value. "always" works everywhere, the others only
// resolve in the event that provides that data (a level-up, a giveaway, a bump reminder, a
// triggering message, or a custom command). Variables marked dynamic are handled by patterns or
// by the feature that owns them, not by an exact key in the engine.

const VARIABLE_GROUPS = [
  {
    id: 'user',
    label: 'User dot notation',
    availability: 'always',
    vars: [
      { tok: '{user}', desc: 'Mentions the user' },
      { tok: '{user.mention}', desc: 'Mentions the user (same as {user})' },
      { tok: '{user.name}', desc: 'Username' },
      { tok: '{user.id}', desc: 'User ID' },
      { tok: '{user.avatar}', desc: 'Global avatar image URL' },
      { tok: '{user.display_avatar}', desc: 'Server avatar, falls back to global' },
      { tok: '{user.display_name}', desc: 'Server nickname, or username if none' },
      { tok: '{user.joined_at}', desc: 'Date they joined this server' },
      { tok: '{user.joined_at_timestamp}', desc: 'Unix timestamp of that join date' },
      { tok: '{user.created_at}', desc: 'Date the account was created' },
      { tok: '{user.created_at_timestamp}', desc: 'Unix timestamp of account creation' },
      { tok: '{user.boost}', desc: '"Yes" or "No", are they boosting' },
      { tok: '{user.boost_since}', desc: 'Date they started boosting, or "Not boosting"' },
      { tok: '{user.boost_since_timestamp}', desc: 'Unix timestamp of boost start' },
      { tok: '{user.color}', desc: 'Highest role color as hex' },
      { tok: '{user.top_role}', desc: 'Their highest role name' },
      { tok: '{user.role_list}', desc: 'All their roles, mentioned' },
      { tok: '{user.bot}', desc: '"Yes" or "No", is it a bot account' },
      { tok: '{user.join_position}', desc: 'Which member number they were' },
      { tok: '{user.join_position_suffix}', desc: 'Join position with suffix (1st, 2nd...)' },
    ],
  },
  {
    id: 'user_legacy',
    label: 'User (legacy)',
    availability: 'always',
    vars: [
      { tok: '{user_tag}', desc: 'Username (same as {user.name})' },
      { tok: '{user_name}', desc: 'Username' },
      { tok: '{user_avatar}', desc: 'Avatar image URL' },
      { tok: '{user_id}', desc: 'User ID' },
      { tok: '{user_discrim}', desc: 'Discriminator, mostly empty on new usernames' },
      { tok: '{user_nick}', desc: 'Server nickname, or username if none' },
      { tok: '{user_joindate}', desc: 'Date they joined this server' },
      { tok: '{user_createdate}', desc: 'Date the account was created' },
      { tok: '{user_displaycolor}', desc: 'Highest role color as hex' },
      { tok: '{user_boostsince}', desc: 'Date they started boosting, or "Not boosting"' },
    ],
  },
  {
    id: 'server',
    label: 'Server',
    availability: 'always',
    vars: [
      { tok: '{server_name}', desc: 'Server name' },
      { tok: '{server_id}', desc: 'Server ID' },
      { tok: '{server_prefix}', desc: 'The server\'s configured prefix' },
      { tok: '{server_membercount}', desc: 'Total member count' },
      { tok: '{server_membercount_ordinal}', desc: 'Member count with suffix (1st, 2nd...)' },
      { tok: '{server_membercount_nobots}', desc: 'Member count excluding bots' },
      { tok: '{server_membercount_nobots_ordinal}', desc: 'That count, with suffix' },
      { tok: '{server_botcount}', desc: 'Number of bots in the server' },
      { tok: '{server_botcount_ordinal}', desc: 'Bot count, with suffix' },
      { tok: '{server_icon}', desc: 'Server icon URL' },
      { tok: '{server_rolecount}', desc: 'Number of roles' },
      { tok: '{server_channelcount}', desc: 'Number of channels' },
      { tok: '{server_randommember}', desc: 'Mentions a random member' },
      { tok: '{server_randommember_tag}', desc: 'Username of a random member' },
      { tok: '{server_randommember_nobots}', desc: 'Mentions a random non-bot member' },
      { tok: '{server_owner}', desc: 'Mentions the server owner' },
      { tok: '{server_owner_id}', desc: 'Server owner\'s user ID' },
      { tok: '{server_createdate}', desc: 'Date the server was created' },
      { tok: '{server_boostlevel}', desc: 'Current boost level (0-3)' },
      { tok: '{server_boostcount}', desc: 'Total boost count' },
      { tok: '{server_nextboostlevel}', desc: 'The next boost level (1-3)' },
      { tok: '{server_nextboostlevel_required}', desc: 'Boosts required to reach it' },
      { tok: '{server_nextboostlevel_until_required}', desc: 'Boosts still needed to reach it' },
    ],
  },
  {
    id: 'guild',
    label: 'Guild dot notation',
    availability: 'always',
    vars: [
      { tok: '{guild.name}', desc: 'Server name' },
      { tok: '{guild.id}', desc: 'Server ID' },
      { tok: '{guild.count}', desc: 'Total member count' },
      { tok: '{guild.icon}', desc: 'Server icon URL' },
      { tok: '{guild.banner}', desc: 'Server banner URL' },
      { tok: '{guild.owner_id}', desc: 'Server owner\'s user ID' },
      { tok: '{guild.created_at}', desc: 'Date the server was created' },
      { tok: '{guild.created_at_timestamp}', desc: 'Unix timestamp of server creation' },
      { tok: '{guild.emoji_count}', desc: 'Number of custom emojis' },
      { tok: '{guild.role_count}', desc: 'Number of roles' },
      { tok: '{guild.boost_count}', desc: 'Total boost count' },
      { tok: '{guild.boost_tier}', desc: 'Boost tier, e.g. "Level 2" or "No Level"' },
      { tok: '{guild.channels_count}', desc: 'Number of channels' },
      { tok: '{guild.vanity}', desc: 'Vanity invite URL, if the server has one' },
      { tok: '{guild.region}', desc: 'Server\'s preferred locale' },
      { tok: '{guild.max_members}', desc: 'Max member capacity' },
    ],
  },
  {
    id: 'channel',
    label: 'Channel',
    availability: 'always',
    vars: [
      { tok: '{channel}', desc: 'Mentions the current channel' },
      { tok: '{channel.mention}', desc: 'Mentions the current channel' },
      { tok: '{channel.name}', desc: 'Channel name' },
      { tok: '{channel.id}', desc: 'Channel ID' },
      { tok: '{channel.topic}', desc: 'Channel topic' },
      { tok: '{channel_name}', desc: 'Channel name (legacy)' },
      { tok: '{channel_createdate}', desc: 'Date the channel was created (legacy)' },
    ],
  },
  {
    id: 'message',
    label: 'Message',
    availability: 'message',
    vars: [
      { tok: '{message_link}', desc: 'Only where a triggering message exists (e.g. autoresponders)' },
      { tok: '{message_id}', desc: 'ID of the triggering message' },
      { tok: '{message_content}', desc: 'Text of the triggering message' },
    ],
  },
  {
    id: 'leveling',
    label: 'Leveling',
    availability: 'leveling',
    vars: [
      { tok: '{level}', desc: 'In the level-up message and the rank card: the level' },
      { tok: '{level_next}', desc: 'The next level' },
      { tok: '{level_xp}', desc: 'Total XP' },
      { tok: '{level_xp_current}', desc: 'XP earned in the current level' },
      { tok: '{level_xp_needed}', desc: 'XP needed to go from this level to the next' },
      { tok: '{level_xp_to_next}', desc: 'XP still missing for the next level' },
      { tok: '{level_progress}', desc: 'Progress to the next level, 0 to 100' },
      { tok: '{level_rank}', desc: 'Leaderboard position' },
      { tok: '{level_rank_total}', desc: 'Members on the leaderboard' },
      { tok: '{level_streak}', desc: 'Days in a row with activity' },
      { tok: '{level_messages}', desc: 'Messages counted' },
      { tok: '{level_voice_minutes}', desc: 'Minutes in voice counted' },
      { tok: '{level_type}', desc: 'text or voice' },
    ],
  },
  {
    id: 'giveaway',
    label: 'Giveaway',
    availability: 'giveaway',
    vars: [
      { tok: '{gw.prize}', desc: 'The prize' },
      { tok: '{gw.winners}', desc: 'Number of winners' },
      { tok: '{gw.entries}', desc: 'Current number of entries' },
      { tok: '{gw.host}', desc: 'Mentions whoever started it' },
      { tok: '{gw.host_name}', desc: 'The host\'s username' },
      { tok: '{gw.host_avatar}', desc: 'The host\'s avatar image URL' },
      { tok: '{gw.duration}', desc: 'End time, as a raw unix timestamp' },
      { tok: '{gw.timestamp}', desc: 'End time, as a relative Discord timestamp' },
      { tok: '{gw.ends}', desc: 'End time as a relative Discord timestamp' },
      { tok: '{gw.claim_time}', desc: 'How long winners have to claim' },
      { tok: '{gw.reaction}', desc: 'The entry emoji, if using reaction mode' },
      { tok: '{gw.entry_mode}', desc: '"react with" or "click on", matches entry mode' },
      { tok: '{gw.entry_text}', desc: 'Entry instruction, based on the selected method' },
      { tok: '{gw.winner_text}', desc: 'Winner-count text used by the giveaway' },
      { tok: '{gw.status}', desc: 'Active or Ended' },
      { tok: '{gw.preset}', desc: 'The bonus-entry roles list, if a preset is used' },
    ],
  },
  {
    id: 'command',
    label: 'Custom Commands',
    availability: 'command',
    vars: [
      { tok: '{args}', desc: 'All text after the command name' },
      { tok: '{arguments}', desc: 'Alias for {args}' },
      { tok: '{args_raw}', desc: 'Alias for {args}; keeps the full argument text' },
      { tok: '{arg1}', desc: 'First argument', dynamic: true },
      { tok: '{arg2}', desc: 'Second argument', dynamic: true },
      { tok: '{arg3}', desc: 'Third argument', dynamic: true },
      { tok: '{arg4}', desc: 'Fourth argument', dynamic: true },
      { tok: '{arg5}', desc: 'Fifth argument', dynamic: true },
      { tok: '{arg6}', desc: 'Sixth argument', dynamic: true },
      { tok: '{arg7}', desc: 'Seventh argument', dynamic: true },
      { tok: '{arg8}', desc: 'Eighth argument', dynamic: true },
      { tok: '{arg9}', desc: 'Ninth argument', dynamic: true },
      { tok: '{arg10}', desc: 'Tenth argument', dynamic: true },
      { tok: '{args_from:2}', desc: 'All arguments starting at the given position', dynamic: true },
      { tok: '{arg_count}', desc: 'Number of arguments supplied' },
      { tok: '{command_name}', desc: 'The command name that was used' },
      { tok: '{prefix}', desc: 'The prefix that was used' },
      { tok: '{reactreply:emoji}', desc: 'Response flag: reacts to the sent message with this emoji; repeat it for more reactions', dynamic: true },
    ],
  },
  {
    id: 'sanction',
    label: 'Sanction',
    availability: 'sanction',
    vars: [
      { tok: '{case.id}', desc: 'The case number (not in the message sent to the member before a ban, kick or similar)' },
      { tok: '{case.type}', desc: 'ban, tempban, softban, unban, kick, mute, tempmute, unmute, warn, jail or unjail' },
      { tok: '{case.action}', desc: 'The action in words, such as "banned from" or "warned in"' },
      { tok: '{case.emoji}', desc: 'The icon of the action' },
      { tok: '{case.reason}', desc: 'The reason' },
      { tok: '{case.duration}', desc: 'How long it lasts, or Permanent' },
      { tok: '{case.expires}', desc: 'When it ends, as a relative time, or Never' },
      { tok: '{case.expires_at}', desc: 'When it ends, as a date and time, or Never' },
      { tok: '{case.source}', desc: 'Who applied it: a moderator, automod, the honeypot, warn escalation or an automatic expiry' },
      { tok: '{case.moderator}', desc: 'Mentions the moderator' },
      { tok: '{case.moderator_name}', desc: 'Name of the moderator' },
      { tok: '{case.moderator_id}', desc: 'ID of the moderator' },
      { tok: '{case.moderator_avatar}', desc: 'Avatar of the moderator' },
      { tok: '{case.user}', desc: 'Mentions the sanctioned member' },
      { tok: '{case.user_name}', desc: 'Name of the sanctioned member' },
      { tok: '{case.user_id}', desc: 'ID of the sanctioned member' },
      { tok: '{case.user_avatar}', desc: 'Avatar of the sanctioned member' },
    ],
  },
  {
    id: 'starboard',
    label: 'Starboard',
    availability: 'starboard',
    vars: [
      { tok: '{star.count}', desc: 'Number of stars' },
      { tok: '{star.emoji}', desc: 'The starboard emoji' },
      { tok: '{star.channel}', desc: 'Mentions the channel of the message' },
      { tok: '{star.channel_name}', desc: 'Name of that channel' },
      { tok: '{star.link}', desc: 'Link to the starred message' },
      { tok: '{star.message_id}', desc: 'ID of the starred message' },
      { tok: '{star.author}', desc: 'Mentions the author of the message' },
      { tok: '{star.author_name}', desc: 'Name of the author' },
      { tok: '{star.author_id}', desc: 'ID of the author' },
      { tok: '{star.author_avatar}', desc: 'Avatar of the author' },
      { tok: '{star.content}', desc: 'Text of the message' },
      { tok: '{star.image}', desc: 'Link of the first image of the message, empty if none' },
      { tok: '{star.attachments}', desc: 'Links to the other files of the message' },
      { tok: '{star.time}', desc: 'When the message was sent' },
    ],
  },
  {
    id: 'verification',
    label: 'Verification',
    availability: 'verification',
    vars: [
      { tok: '{verify.link}', desc: 'Only in the verification message: the link the member opens to verify' },
    ],
  },
  {
    id: 'quest',
    label: 'Quests',
    availability: 'quest',
    vars: [
      { tok: '{quest.name}', desc: 'Name of the quest' },
      { tok: '{quest.game}', desc: 'The game or brand' },
      { tok: '{quest.publisher}', desc: 'Who published it' },
      { tok: '{quest.id}', desc: 'ID of the quest' },
      { tok: '{quest.url}', desc: 'Link to accept the quest in Discord' },
      { tok: '{quest.link}', desc: 'Link to the game or brand page, empty if none' },
      { tok: '{quest.image}', desc: 'Banner picture of the quest, empty if none' },
      { tok: '{quest.logo}', desc: 'Logo of the game, empty if none' },
      { tok: '{quest.color}', desc: 'Main color of the quest as hex' },
      { tok: '{quest.reward}', desc: 'The rewards, with their type' },
      { tok: '{quest.reward_type}', desc: 'Type of the first reward: Orbs, Collectible, Code...' },
      { tok: '{quest.reward_amount}', desc: 'Number of Orbs, empty if the reward is not Orbs' },
      { tok: '{quest.reward_image}', desc: 'Picture of the first reward, empty if none' },
      { tok: '{quest.task}', desc: 'The first task, such as Watch a video' },
      { tok: '{quest.task_minutes}', desc: 'Minutes the first task takes' },
      { tok: '{quest.tasks}', desc: 'All the tasks with their time' },
      { tok: '{quest.platforms}', desc: 'Where it can be done: Desktop, Mobile, Xbox...' },
      { tok: '{quest.starts}', desc: 'When it starts, as a relative time' },
      { tok: '{quest.starts_at}', desc: 'When it starts, as a date and time' },
      { tok: '{quest.expires}', desc: 'When it ends, as a relative time' },
      { tok: '{quest.expires_at}', desc: 'When it ends, as a date and time' },
      { tok: '{quest.limits}', desc: 'Region and age limits, or None' },
      { tok: '{quest.age_gate}', desc: '18+ when it has an age limit, otherwise empty' },
      { tok: '{quest.status}', desc: 'New quest, or Ending soon' },
      { tok: '{quest.source}', desc: 'discordquest.com' },
    ],
  },
  {
    id: 'bump',
    label: 'Bump',
    availability: 'bump',
    vars: [
      { tok: '{user.mention}', desc: 'Only in bump messages: mentions whoever bumped' },
      { tok: '{nextBump}', desc: 'Only in bump messages: relative time until the next bump is allowed', dynamic: true },
    ],
  },
  {
    id: 'date',
    label: 'Date',
    availability: 'always',
    vars: [
      { tok: '{date}', desc: 'Today\'s date' },
      { tok: '{date.now}', desc: 'Today\'s date, Pacific time' },
      { tok: '{date.utc_now}', desc: 'Current date and time, UTC' },
      { tok: '{date.utc_timestamp}', desc: 'Current unix timestamp' },
    ],
  },
  {
    id: 'functions',
    label: 'Functions',
    availability: 'always',
    vars: [
      { tok: '{choose:a|b|c}', desc: 'Picks one option at random each time', dynamic: true },
      { tok: '{range:1-100}', desc: 'A random whole number in that range', dynamic: true },
      { tok: '{newline}', desc: 'Forces a line break' },
      { tok: '{separator}', desc: 'A decorative divider line' },
    ],
  },
  {
    id: 'actions',
    label: 'Actions',
    availability: 'always',
    vars: [
      { tok: '{reactreply:emoji}', desc: 'Reacts to the sent message with this emoji. If the response contains only this flag, it reacts to the triggering message instead.', dynamic: true },
    ],
  },
];

function listVariables() {
  return VARIABLE_GROUPS.map((group) => ({ ...group, vars: group.vars.map((variable) => ({ ...variable })) }));
}

module.exports = { VARIABLE_GROUPS, listVariables };
